default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: cine_market_development

test:
  <<: *default
  database: cine_market_test

production:
  primary:
    <<: *default
    database: cine_market_production
    url: <%= ENV['DATABASE_URL'] %>
  cable:
    <<: *default
    database: cine_market_production
    url: <%= ENV['DATABASE_URL'] %>
    migrations_paths: db/cable_migrate